export const SelectTheme = {
  '--background-color-active': 'var(--hdbt-color-black)',
  '--background-color-focus': 'var(--hdbt-color-black)',
  '--background-color-hover': 'var(--hdbt-color-black)',
  '--background-color': 'var(--hdbt-color-black)',
  '--border-color-active': 'var(--hdbt-color-black)',
  '--border-color-focus': 'var(--hdbt-color-black)',
  '--border-color-hover': 'var(--hdbt-color-black)',
  '--border-color': 'var(--hdbt-color-black)',
  '--checkbox-background-hover': 'var(--hdbt-color-black)',
  '--checkbox-background-selected': 'var(--hdbt-color-black)',
  '--checkbox-border-color-selected-hover': 'var(--hdbt-color-black)',
  '--checkbox-icon-color-selected': 'var(--color-white)',
  '--color-active': 'var(--color-white)',
  '--color-focus': 'var(--color-white)',
  '--color-hover': 'var(--color-white)',
  '--color': 'var(--color-white)',
  '--menu-item-background-color-hover': 'var(--hdbt-color-black)',
  '--menu-item-background-color-selected-hover': 'var(--hdbt-color-black)',
  '--menu-item-color-hover': 'var(--color-white)',
  '--menu-item-color-selected-hover': 'var(--color-white)',
  '--outline-color-focus': 'var(--hdbt-color-black)',
};
