<?php

/**
 * @file
 * Primary module hooks for Paatokset RSS module.
 */

declare(strict_types=1);

use Drupal\paatokset_rss\ItemsImporter;
use Drupal\paatokset_rss\ItemsStorage;

/**
 * Implements hook_cron().
 */
function paatokset_rss_cron() : void {
  /** @var \Drupal\paatokset_rss\ItemsImporter $importer */
  $importer = \Drupal::service(ItemsImporter::class);

  foreach (['fi', 'en', 'sv'] as $langcode) {
    $data = $importer->fetch($langcode);

    \Drupal::service(ItemsStorage::class)
      ->save($langcode, $data);
  }
}

/**
 * Implements hook_theme().
 */
function paatokset_rss_theme() : array {
  return [
    'paatokset_rss_item' => [
      'variables' => [
        'item' => NULL,
      ],
      'template' => 'paatokset-rss-item',
    ],
  ];
}
