services:
  db:
    command:
      - --max_allowed_packet=512M
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_swedish_ci
      - --sort_buffer_size=4096k
  app:
    environment:
      ALLU_USERNAME: ${ALLU_USERNAME}
      ALLU_BASE_URL: ${ALLU_BASE_URL}
      ALLU_PASSWORD: ${ALLU_PASSWORD}
      DRUPAL_REVERSE_PROXY_ADDRESS: helsinki-paatokset.docker.so
      OPERATOR_GUIDE_NODE_ID: 220913
    env_file:
      - .env.local
