version: '3.7'

services:
  app:
    hostname: "${DRUPAL_HOSTNAME}"
    container_name: "${COMPOSE_PROJECT_NAME}-app"
    image: "${DRUPAL_IMAGE}"
    volumes:
      - .:/app:delegated
      - ssh:/tmp/druid_ssh-agent:ro
    depends_on:
      - db
    environment:
      APP_ENV: "${APP_ENV:-local}"
      DRUPAL_ROUTES: "https://varnish-${DRUPAL_HOSTNAME},http://${COMPOSE_PROJECT_NAME}-varnish"
      DRUSH_OPTIONS_URI: "https://${DRUPAL_HOSTNAME}"
      # To enable xdebug, run `export XDEBUG_ENABLE=true` before (re)starting your project.
      # Optionally, you can add this to your default environments variables to enable or disable
      # xdebug by default (like /etc/environments, ~/.bashrc, or ~/.zshrc).
      XDEBUG_ENABLE: "${XDEBUG_ENABLE:-false}"
      SIMPLETEST_BASE_URL: "http://127.0.0.1:8888"
      SIMPLETEST_DB: "mysql://drupal:drupal@db:3306/drupal"
      BROWSERTEST_OUTPUT_BASE_URL: "https://${DRUPAL_HOSTNAME}"
      DRUPAL_VARNISH_HOST: "${COMPOSE_PROJECT_NAME}-varnish"
      DRUPAL_VARNISH_PORT: 6081
      REDIS_HOST: redis
      PROJECT_NAME: "${PROJECT_NAME}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "${DRUPAL_HOSTNAME}:host-gateway"
    env_file:
      - .env
      - .env.local
    networks:
      - internal
      - stonehenge-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.entrypoints=https"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.rule=Host(`${DRUPAL_HOSTNAME}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.tls=true"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-app.loadbalancer.server.port=8080"
      - "traefik.docker.network=stonehenge-network"
  redis:
    container_name: "${COMPOSE_PROJECT_NAME}-redis"
    image: redis:7-alpine
    command: [sh, -c, "rm -f /data/dump.rdb && redis-server --save ''"]
    networks:
      - internal
  db:
    container_name: "${COMPOSE_PROJECT_NAME}-db"
    image: druidfi/mariadb:10.11-drupal
    environment:
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_INITDB_SKIP_TZINFO: "1"
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306
    networks:
      - internal
  varnish:
    container_name: "${COMPOSE_PROJECT_NAME}-varnish"
    image: druidfi/varnish:6-drupal
    environment:
      VARNISH_BACKEND_HOST: "${COMPOSE_PROJECT_NAME}-app"
    depends_on:
      - app
    networks:
      - internal
      - stonehenge-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-varnish.entrypoints=https"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-varnish.rule=Host(`varnish-${DRUPAL_HOSTNAME}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-varnish.tls=true"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-varnish.loadbalancer.server.port=6081"
      - "traefik.docker.network=stonehenge-network"
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    container_name: "${COMPOSE_PROJECT_NAME}-elastic"
    environment:
      - node.name="${COMPOSE_PROJECT_NAME}-elastic"
      - discovery.seed_hosts=elastic
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes="${COMPOSE_PROJECT_NAME}-elastic"
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.cors.allow-origin=*"
      - "http.cors.enabled=true"
      - "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
      - "http.cors.allow-credentials=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - internal
      - stonehenge-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-elastic.entrypoints=https"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-elastic.rule=Host(`elastic-${DRUPAL_HOSTNAME}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-elastic.tls=true"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-elastic.loadbalancer.server.port=9200"
      - "traefik.docker.network=stonehenge-network"
      - "traefik.port=9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.1
    container_name: "${COMPOSE_PROJECT_NAME}-kibana"
    environment:
      ELASTICSEARCH_HOSTS: http://elastic:9200
    ports:
      - 5601:5601
    networks:
      - internal
      - stonehenge-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-kibana.entrypoints=https"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-kibana.rule=Host(`kibana-${DRUPAL_HOSTNAME}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-kibana.tls=true"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-kibana.loadbalancer.server.port=5601"
      - "traefik.docker.network=stonehenge-network"
      - "traefik.port=5601"

networks:
  internal:
    external: false
  stonehenge-network:
    external: true

volumes:
  data01:
    driver: local
  db_data:
  ssh:
    name: stonehenge-ssh
    external: true
