pipeline:
  - name: Clean old environment
    type: command
    command: rm -rf vendor/ && rm composer.lock || true
    directory: $APP_ROOT

  - name: Re-install platform
    type: command
    command: composer install
    directory: $APP_ROOT

  - name: Drush site-install
    type: command
    command: drush -y site-install minimal
    directory: $HTTP_ROOT

  - name: Enable all modules
    type: command
    command: drush -y pm:enable helfi_platform_config helfi_base_config helfi_tpr helfi_tunnistamo && drush -y cr
    directory: $HTTP_ROOT

  - name: Update translations
    type: command
    command: drush helfi:locale-import helfi_platform_config
    directory: $HTTP_ROOT

  - name: Reset admin user password
    type: command
    command: drush user:password $DRUPAL_USER_NAME $DRUPAL_USER_PASS
    directory: $HTTP_ROOT

  - name: Drush clear cache
    type: command
    command: drush -y cr
    directory: $HTTP_ROOT
