export const CategoryMap = [
  {"label": "Förvaltningsärenden", "value": "00"},
  {"label": "Personalärenden", "value": "01"},
  {"label": "Ekonomi, beskattning och egendomsförvaltning", "value": "02"},
  {"label": "Lagstiftning och dess tillämpning", "value": "03"},
  {"label": "Internationell verksamhet och migrationspolitik", "value": "04"},
  {"label": "Socialvård", "value": "05"},
  {"label": "Hälsovård", "value": "06"},
  {"label": "Informationshantering", "value": "07"},
  {"label": "Trafik", "value": "08"},
  {"label": "Säkerhet och allmän ordning", "value": "09"},
  {"label": "Markanvändning, byggande och boende", "value": "10"},
  {"label": "Miljöärenden", "value": "11"},
  {"label": "Undervisnings- och bildningsväsende", "value": "12"},
  {"label": "Forskning och utveckling", "value": "13"},
  {"label": "Näringslivs- och arbetskraftstjänster", "value": "14"},
  {"label": "Hallintoasiat", "value": "00"},
  {"label": "Henkilöstöasiat", "value": "01"},
  {"label": "Talousasiat, verotus ja omaisuuden hallinta", "value": "02"},
  {"label": "Lainsäädäntö ja lainsäädännön soveltaminen", "value": "03"},
  {"label": "Kansainvälinen toiminta ja maahanmuuttopolitiikka", "value": "04"},
  {"label": "Sosiaalitoimi", "value": "05"},
  {"label": "Terveydenhuolto", "value": "06"},
  {"label": "Tiedon hallinta", "value": "07"},
  {"label": "Liikenne", "value": "08"},
  {"label": "Turvallisuus ja yleinen järjestys", "value": "09"},
  {"label": "Maankäyttö, rakentaminen ja asuminen", "value": "10"},
  {"label": "Ympäristöasia", "value": "11"},
  {"label": "Opetus- ja sivistystoimi", "value": "12"},
  {"label": "Tutkimus- ja kehittämistoiminta", "value": "13"},
  {"label": "Elinkeino- ja työvoimapalvelut", "value": "14"}
];

export default CategoryMap;
