const searchApiFields = {
  'SEARCH_API_DATASOURCE': 'search_api_datasource',
  'SEARCH_API_ID': 'search_api_id',
  'SEARCH_API_LANGUAGE': 'search_api_language',
};

export const DecisionIndex = {
  ...searchApiFields,
  CATEGORY_NAME: 'category_name',
  COLOR_CLASS: 'color_class',
  DECISION_CONTENT: 'decision_content',
  DECISION_MOTION: 'decision_motion',
  DECISION_URL: 'decision_url',
  HAS_TRANSLATION: 'has_translation',
  ID: 'id',
  IS_DECISION: 'field_is_decision',
  ISSUE_ID: 'issue_id',
  ISSUE_SUBJECT: 'issue_subject',
  LANGUAGE: '_language',
  MEETING_DATE: 'meeting_date',
  MEETING_POLICYMAKER_LINK: 'meeting_policymaker_link',
  ORG_ABOVE: 'organization_above_name',
  ORG_NAME: 'organization_name',
  ORG_TYPE: 'organization_type',
  POLICYMAKER_ID: 'field_policymaker_id',
  POLICYMAKER_STRING: 'decisionmaker_searchfield_data',
  SCORE: '_score',
  SECTION: 'field_decision_section',
  SECTOR_ID: 'sector_id',
  SPECIAL_STATUS: 'special_status',
  STATUS: 'status',
  SUBJECT_RESOLUTION: 'subject_resolution',
  SUBJECT: 'subject',
  TOP_CATEGORY_CODE: 'top_category_code',
  TOP_CATEGORY_NAME: 'top_category_name',
  UID: 'uid',
  UNIQUE_ISSUE_ID: 'unique_issue_id',
};

export const PolicymakerIndex = {
  ...searchApiFields,
  'FIELD_POLICYMAKER_EXISTING': 'field_policymaker_existing',
  'COLOR_CLASS': 'color_class',
  'DECISIONMAKER_COMBINED_TITLE': 'decisionmaker_combined_title',
  'DECISIONMAKER_SEARCHFIELD_DATA': 'decisionmaker_searchfield_data',
  'FIELD_FIRST_NAME': 'field_first_name',
  'HAS_TRANSLATION': 'has_translation',
  'FIELD_POLICYMAKER_ID': 'field_policymaker_id',
  'FIELD_LAST_NAME': 'field_last_name',
  'ORGANIZATION_HIERARCHY': 'organization_hierarchy',
  'FIELD_DM_ORG_NAME': 'field_dm_org_name',
  'FIELD_ORGANIZATION_TYPE': 'field_organization_type',
  'TITLE': 'title',
  'FIELD_SECTOR_NAME': 'field_sector_name',
  'STATUS': 'status',
  'TRUSTEE_NAME': 'trustee_name',
  'TRUSTEE_TITLE': 'trustee_title',
  'UID': 'uid',
};

