# Test services and overrides.
parameters:
  helfi_api_base.internal_domains:
    - 'hel.fi'
    - 'www.hel.fi'
    - 'paatokset.hel.fi'
    - 'avustukset.hel.fi'
    - 'nginx-paatokset-prod.apps.platta.hel.fi'
