# Test services and overrides.
parameters:
  helfi_api_base.logger_enabled: false
  helfi_api_base.internal_domains:
    - 'paatokset.hel.fi'
    - 'nginx-paatokset-prod.apps.platta.hel.fi'
    - 'helsinki-paatokset.docker.so'
