<?php

/**
 * @file
 * Primary module hooks for Datapumppu API module.
 */

declare(strict_types=1);

use Drupal\Core\Cache\CacheTagsInvalidatorInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\paatokset_datapumppu\Entity\Statement;

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function paatokset_datapumppu_paatokset_statement_insert(EntityInterface $entity): void {
  _paatokset_datapumppu_invalidate_statement_cache_tags($entity);
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function paatokset_datapumppu_paatokset_statement_update(EntityInterface $entity): void {
  _paatokset_datapumppu_invalidate_statement_cache_tags($entity);
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function paatokset_datapumppu_paatokset_statement_delete(EntityInterface $entity): void {
  _paatokset_datapumppu_invalidate_statement_cache_tags($entity);
}

/**
 * Invalidates custom cache tags for statement.
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *   Entity to base cache invalidations on.
 */
function _paatokset_datapumppu_invalidate_statement_cache_tags(EntityInterface $entity): void {
  assert($entity instanceof Statement);

  $trustee_id = $entity->getSpeakerId();

  $tags = [];
  if ($trustee_id) {
    $tags[] = "trustee_statements:$trustee_id";
  }

  if (!empty($tags)) {
    /** @var Drupal\Core\Cache\CacheTagsInvalidator $cache_invalidator */
    $cache_invalidator = \Drupal::service(CacheTagsInvalidatorInterface::class);
    $cache_invalidator->invalidateTags($tags);
  }
}
