<?php

/**
 * @file
 * Primary module hooks for Ahjo API module.
 */

declare(strict_types = 1);

/**
 * Callback to check if array or text value is empty.
 *
 * @param mixed $value
 *   The value to work with.
 *
 * @return bool
 *   TRUE is value is not empty, FALSE if it is.
 */
function _paatokset_ahjo_api_true_if_not_empty($value): bool {
  return !empty($value);
}

/**
 * Callback to check if meeting minutes have been published
 *
 * @param mixed $documents
 *   An array of meeting documents.
 *
 * @return bool
 *   TRUE is thee minutes are found, FALSE if they are not.
 */
function _paatokset_ahjo_api_meeting_minutes_published($documents): bool {
  if (empty($documents) || !is_array($documents)) {
    return FALSE;
  }

  foreach ($documents as $document) {
    if (isset($document['Type']) && $document['Type'] === 'pöytäkirja') {
      return TRUE;
    }
  }

  return FALSE;
}

/**
 * Update diary number and diary number label field max lengths.
 */
function paatokset_ahjo_api_update_9001() {
  // Update case diary number max length.
  $database = \Drupal::database();
  $database->query("ALTER TABLE node__field_diary_number MODIFY field_diary_number_value VARCHAR(255)");
  $database->query("ALTER TABLE node_revision__field_diary_number MODIFY field_diary_number_value VARCHAR(255)");
  $storage_key = 'node.field_schema_data.field_diary_number';
  $storage_schema = \Drupal::keyValue('entity.storage_schema.sql');
  $field_schema = $storage_schema->get($storage_key);
  $field_schema['node__field_diary_number']['fields']['field_diary_number_value']['length'] = 255;
  $field_schema['node_revision__field_diary_number']['fields']['field_diary_number_value']['length'] = 255;
  $storage_schema->set($storage_key, $field_schema);

  // Update case diary label number max length.
  $database = \Drupal::database();
  $database->query("ALTER TABLE node__field_diary_number_label MODIFY field_diary_number_label_value VARCHAR(255)");
  $database->query("ALTER TABLE node_revision__field_diary_number_label MODIFY field_diary_number_label_value VARCHAR(255)");
  $storage_key = 'node.field_schema_data.field_diary_number_label';
  $storage_schema = \Drupal::keyValue('entity.storage_schema.sql');
  $field_schema = $storage_schema->get($storage_key);
  $field_schema['node__field_diary_number']['fields']['field_diary_number_label_value']['length'] = 255;
  $field_schema['node_revision__field_diary_number']['fields']['field_diary_number_label_value']['length'] = 255;
  $storage_schema->set($storage_key, $field_schema);
}
