<?php

/**
 * @file
 * Primary module hooks for Paatokset search module.
 */

declare(strict_types = 1);

/**
 * Implements hook_preprocess_html().
 */
function paatokset_search_preprocess_html(array &$variables) {
  if (str_contains(\Drupal::routeMatch()->getRouteName(), 'paatokset_search.decisions')) {
    $variables['attributes']['class'][] = 'paatokset-search-page--decisions';
  }
}

/**
 * Implements hook_elasticsearch_connector_load_library_options_alter().
 *
 * Set cURL options to trust self-signed certificate.
 *
 * @fixme rather than disabling verification, should set CURLOPT_SSLCERT to correct value.
 */
function paatokset_search_elasticsearch_connector_load_library_options_alter(&$options, &$context) {
  $options['curl'][CURLOPT_SSL_VERIFYPEER] = FALSE;
  $options['curl'][CURLOPT_SSL_VERIFYHOST] = FALSE;
}

/**
 * Implements hook_preprocess__HOOK().
 */
function paatokset_search_preprocess_block__policymaker_search_block(array &$variables) {
  $variables['elastic_url'] = getenv('REACT_APP_ELASTIC_URL');
}
