<?php

/**
 * @file
 * Contains paatokset_ahjo.
 */

use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Render\Element;
use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\paatokset_ahjo\Service\IssueService;

/**
 * Implements hook_theme().
 */
function paatokset_ahjo_theme($existing, $type, $theme, $path) {
  return [
    'paatokset_issue' => [
      'render element' => 'elements',
      'template' => 'paatokset-issue',
    ],
    'paatokset_policymaker' => [
      'render element' => 'elements',
      'template' => 'paatokset-policymaker',
    ],
    'paatokset_organization' => [
      'render element' => 'elements',
      'template' => 'paatokset-organization',
    ],
    'paatokset_meeting_document' => [
      'render element' => 'elements',
      'template' => 'paatokset-meeting-document',
    ],
    'paatokset_agenda_item' => [
      'render element' => 'elements',
      'template' => 'paatokset-agenda-item',
    ],
    'tpr_unit__contact_card' => [
      'base hook' => 'entity',
      'template' => 'content/tpr-unit--contact-card',
    ],

  ];
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function paatokset_ahjo_theme_suggestions_paatokset_issue(array $variables) {
  $suggestions = [];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'paatokset_issue__' . $sanitized_view_mode;

  return $suggestions;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function paatokset_ahjo_theme_suggestions_paatokset_policymaker(array $variables) {
  $suggestions = [];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'paatokset_policymaker__' . $sanitized_view_mode;

  return $suggestions;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function paatokset_ahjo_theme_suggestions_paatokset_organization(array $variables) {
  $suggestions = [];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'paatokset_organization__' . $sanitized_view_mode;

  return $suggestions;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function paatokset_ahjo_theme_suggestions_paatokset_meeting_document(array $variables) {
  $suggestions = [];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'paatokset_meeting_document__' . $sanitized_view_mode;

  return $suggestions;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function paatokset_ahjo_theme_suggestions_paatokset_agenda_item(array $variables) {
  $suggestions = [];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'paatokset_agenda_item__' . $sanitized_view_mode;

  return $suggestions;
}

/**
 * Prepares variables for paatokset_ahjo templates.
 *
 * Default template: paatokset-issue.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An array of elements to display in view mode.
 */
function template_preprocess_paatokset_issue(array &$variables) {
  $entityTypeIndicator = \Drupal::routeMatch()->getParameters()->keys()[0];
  $entity = \Drupal::routeMatch()->getParameter($entityTypeIndicator);
  if (is_object($entity) && $entity instanceof ContentEntityInterface) {
    $variables['entity'] = $entity;
    $issueService = \Drupal::getContainer()->get(IssueService::class);
    $data = $issueService->getData($entity->get('id')->value);
  }
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  // Helpful $content variable for templates.
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }

  if (isset($data)) {
    foreach ($data as $key => $value) {
      $variables[$key] = $data[$key];
    }
  }
}

/**
 * Prepares variables for paatokset_ahjo templates.
 *
 * Default template: paatokset-policymaker.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An array of elements to display in view mode.
 */
function template_preprocess_paatokset_policymaker(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  // Helpful $content variable for templates.
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
  if (isset($variables['elements']['#paatokset_policymaker'])) {
    $variables['entity'] = $variables['elements']['#paatokset_policymaker'];
  }
}

/**
 * Prepares variables for paatokset_ahjo templates.
 *
 * Default template: paatokset-organization.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An array of elements to display in view mode.
 */
function template_preprocess_paatokset_organization(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  // Helpful $content variable for templates.
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
  if (isset($variables['elements']['#paatokset_organization'])) {
    $variables['entity'] = $variables['elements']['#paatokset_organization'];
  }
}

/**
 * Prepares variables for paatokset_ahjo templates.
 *
 * Default template: paatokset-meeting-document.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An array of elements to display in view mode.
 */
function template_preprocess_paatokset_meeting_document(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  // Helpful $content variable for templates.
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
  if (isset($variables['elements']['#paatokset_meeting_document'])) {
    $variables['entity'] = $variables['elements']['#paatokset_meeting_document'];
  }
}

/**
 * Prepares variables for paatokset_ahjo templates.
 *
 * Default template: paatokset-agenda-item.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An array of elements to display in view mode.
 */
function template_preprocess_paatokset_agenda_item(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  // Helpful $content variable for templates.
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
  if (isset($variables['elements']['#paatokset_agenda_item'])) {
    $variables['entity'] = $variables['elements']['#paatokset_agenda_item'];
  }
}

/**
 * Implements hook_preprocess_tpr_unit__contact_card().
 */
function paatokset_ahjo_preprocess_tpr_unit__contact_card(&$variables) {
  $mapEmbed = $variables['content']['service_map_embed'];

  if (isset($mapEmbed[0]) && isset($mapEmbed[0]['link'])) {
    $variables['content']['service_map_embed_url'] = $mapEmbed[0]['link']['#attributes']['href'];
  }
}

/**
 * Placeholder for city council policymaker ID.
 */
function _paatokset_ahjo_placeholder_policymaker_id($value) {
  if ((string) $value === '5') {
    return '02900';
  }

  return $value;
}
