# Schema for the default text configuration files.
block.settings.policymaker_documents:
  type: block_settings
  label: 'Survey block settings'
  mapping:
    view:
      type: string
    view_display:
      type: string
      nullable: true
paatokset_ahjo_api.default_texts:
  type: config_object
  label: 'Default text configuration'
  mapping:
    calendar_notice_text:
      type: label
      label: 'Frontpage calendar notice text.'
    hidden_decisions_text:
      type: mapping
      label: 'Hidden decisions text'
      mapping:
        value:
          type: text
          label: 'Hidden decisions text - Value'
        format:
          type: string
          label: 'Hidden decisions text - Format'
    non_public_attachments_text:
      type: mapping
      label: 'Non public attachments text'
      mapping:
        value:
          type: text
          label: 'Non public attachments text - Value'
        format:
          type: string
          label: 'Non public attachments text - Format'
    documents_description:
      type: mapping
      label: 'Documents description'
      mapping:
        value:
          type: text
          label: 'Documents description - Value'
        format:
          type: string
          label: 'Documents description - Format'
    meetings_description:
      type: mapping
      label: 'Meetings description'
      mapping:
        value:
          type: text
          label: 'Meetings description - Value'
        format:
          type: string
          label: 'Meetings description - Format'
    recording_description:
      type: mapping
      label: 'Recording description'
      mapping:
        value:
          type: text
          label: 'Recording description - Value'
        format:
          type: string
          label: 'Recording description - Format'
    decisions_description:
      type: mapping
      label: 'Decisions description'
      mapping:
        value:
          type: text
          label: 'Decisions description - Value'
        format:
          type: string
          label: 'Decisions description - Format'
    meeting_calendar_description:
      type: mapping
      label: 'Meeting calendar description'
      mapping:
        value:
          type: text
          label: 'Meeting calendar description - Value'
        format:
          type: string
          label: 'Meeting calendar description - Format'
    decision_search_description:
      type: mapping
      label: 'Decision search description'
      mapping:
        value:
          type: text
          label: 'Decision search description - Value'
        format:
          type: string
          label: 'Decision search description - Format'
    policymakers_search_description:
      type: mapping
      label: 'Policymakers search description'
      mapping:
        value:
          type: text
          label: 'Policymakers search description - Value'
        format:
          type: string
          label: 'Policymakers search description - Format'
    banner_text:
      type: mapping
      label: 'Banner content'
      mapping:
        value:
          type: text
          label: 'Banner content - Value'
        format:
          type: string
          label: 'Banner content - Format'
    banner_heading:
      type: label
      label: 'Banner heading'
    banner_label:
      type: label
      label: 'Banner CTA button label'
    banner_url:
      type: label
      label: 'Banner CTA button URL'
    committees_boards_url:
      type: label
      label: 'Committees and boards URL'
    office_holders_url:
      type: label
      label: 'Office holders URL'
