<?php

/**
 * @file
 * Primary module hooks for Paatokset RSS module.
 */

declare(strict_types=1);

use Drupal\paatokset\Lupapiste\ItemsStorage;

/**
 * Implements hook_theme().
 */
function paatokset_theme() : array {
  return [
    'lupapiste_rss_list' => [
      'variables' => [
        'title' => NULL,
        'content' => NULL,
        'feed_link' => NULL,
      ],
      'template' => 'lupapiste-rss-list',
    ],
    'lupapiste_rss_item' => [
      'variables' => [
        'item' => NULL,
      ],
      'template' => 'lupapiste-rss-item',
    ],
  ];
}

/**
 * Implements hook_cron().
 */
function paatokset_cron() : void {
  // Clear lupapiste RSS-feed cache if it's over 24 hours old (failsafe) or if
  // the RSS feed was updated since the last fetch.
  $lupapiste_storage = \Drupal::getContainer()->get(ItemsStorage::class);
  if ($lupapiste_storage->purgeCacheIfNeeded()) {
    \Drupal::logger('paatokset')->notice('Cleared caches for Lupapiste RSS feed.');
  }
}
