<?php

/**
 * @file
 * Primary module hooks for Paatokset RSS module.
 */

declare(strict_types=1);

/**
 * Implements hook_theme().
 */
function paatokset_theme() : array {
  return [
    'lupapiste_rss_list' => [
      'variables' => [
        'title' => NULL,
        'content' => NULL,
        'feed_link' => NULL,
      ],
      'template' => 'lupapiste-rss-list',
    ],
    'lupapiste_rss_item' => [
      'variables' => [
        'item' => NULL,
      ],
      'template' => 'lupapiste-rss-item',
    ],
  ];
}
