<?php

/**
 * @file
 * Primary module hooks for Ahjo Policymakers module.
 */

declare(strict_types = 1);

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function paatokset_policymakers_theme($existing, $type, $theme, $path) {
  return [
    'node__policymaker' => [
      'render element' => 'elements',
      'template' => 'node--policymaker',
      'path' => $path . '/templates/content',
      'base hook' => 'node',
    ],
    'block__policymaker_calendar' => [
      'base hook' => 'entity',
      'template' => 'block/block--policymaker-calendar',
    ],
    'policymaker_minutes' => [
      'render element' => 'elements',
      'template' => 'content/minutes'
    ],
    'block__policymaker_members' => [
      'base hook' => 'entity',
      'template' => 'block/block--policymaker-members',
    ],
  ];
}

/**
 * Prepares variables for paatokset_ahjo templates.
 *
 * Default template: paatokset-meeting.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An array of elements to display in view mode.
 */
function paatokset_policymakers_preprocess_block__policymaker_calendar(array &$variables) {
  $meetingService = \Drupal::service('paatokset_ahjo_meetings');
  $node = \Drupal::routeMatch()->getParameter('node');

  $params = [
    'policymaker' => $node->get('field_policymaker_id')->value,
    'from' => date("Y-m-d"),
  ];

  // Helpful $content variable for templates.
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
  if (isset($variables['elements']['#block__policymaker_calendar'])) {
    $variables['entity'] = $variables['elements']['#block__policymaker_calendar'];
  }

  $variables['date'] = t('Date');
  $variables['time'] = t('Time');
  $variables['additional_info'] = t('Additional information');
  $variables['open_motions'] = t('Open motions');
  $variables['open_decisions'] = t('Open decisions');
  $variables['open_minutes'] = t('Open minutes');
  $variables['meetings'] = $meetingService->query($params);
  $variables['meetings_description'] = $node->get('field_meetings_description');
}

/**
 * Implements preprocess_node hook.
 */
function paatokset_policymakers_preprocess_node__policymaker(&$variables) {
  /** @var \Drupal\paatokset_policymakers\Service\PolicymakerService $policymakerService */
  $policymakerService = \Drupal::service('paatokset_policymakers');

  /** @var \Drupal\paatokset_ahjo_api\Service\MeetingService $meetingService */
  $meetingService = \Drupal::service('paatokset_ahjo_meetings');
  $councilId = \Drupal::config('paatokset_helsinki_kanava.settings')->get('city_council_id');

  $policymaker = $variables['node'];
  $policymakerService->setPolicyMakerNode($policymaker);
  $variables['organization_type'] = $policymakerService->getPolicymakerTypeFromNode($policymaker);
  $variables['organization_type_color'] = $policymakerService->getPolicymakerClass($policymaker);
  $no_content = TRUE;

  $not_organization_types = [
    'Luottamushenkilö',
    'Viranhaltija',
  ];

  $orgType = $policymaker->get('field_organization_type')->value;

  if ($orgType) {
    if (!in_array($orgType, $not_organization_types)) {
      $variables['is_organization'] = TRUE;
      
      $members = $policymakerService->getComposition();
      if($members) {
        $variables['has_members'] = TRUE;
        $no_content = FALSE;
      }

      $documents = $policymakerService->getApiMinutes(2);
      if ($documents) {
        $variables['recent_documents'] = $documents;
        $variables['all_documents_link'] = $policymakerService->getDocumentsRoute();
        $no_content = FALSE;
      }

      $params = [
        'policymaker' => $policymaker->get('field_policymaker_id')->value,
        'from' => date("Y-m-d"),
      ];
      $upcomingMeetings = $meetingService->query($params);

      if (!empty($upcomingMeetings)) {
        $variables['meeting_calendar'] = TRUE;
        $no_content = FALSE;
      }
    }
    else {
      // Get the two most recent decisions.
      $recentDecisions = $policymakerService->getAgendasList(2, FALSE);
      if (!empty($recentDecisions)) {
        $variables['recent_decisions'] = $recentDecisions;
        $variables['all_decisions_link'] = $policymakerService->getDecisionsRoute();
        $no_content = FALSE;
      }
    }
  }

  if ($councilId && ($policymaker->get('field_policymaker_id')->value === $councilId)) {
    $variables['render_announcement_block'] = TRUE;
    $no_content = FALSE;
  }

  $variables['no_content'] = $no_content;
}

/**
 * Implements preprocess_field hook.
 */
function paatokset_policymakers_preprocess_field__node__title(&$variables) {
  $title = $variables['items'][0]['content']['#context']['value'];
  $node = $variables['element']['#object'];
  $first_name = '';
  $last_name = '';

  if($node->getType() === 'policymaker') {
    if($node->hasField('field_first_name') && !$node->get('field_first_name')->isEmpty()) {
      $first_name = $node->get('field_first_name')->value;
    }
  
    if($node->hasField('field_last_name') && !$node->get('field_last_name')->isEmpty()) {
      $last_name = $node->get('field_last_name')->value;
    }
  
    if(!empty($first_name) || !empty($last_name)) {
      $variables['items'][0]['content']['#context']['value'] = $title . ': ' . $first_name . ' ' . $last_name;
    }
  }
}

/**
 * Implements preprocess hook.
 */
function paatokset_policymakers_preprocess_policymaker_minutes(&$variables) {
  if (isset($variables['elements']['meeting']) && !empty($variables['elements']['meeting'])) {
    $variables['meeting'] = $variables['elements']['meeting'];
  }
  if (isset($variables['elements']['list']) && !empty($variables['elements']['list'])) {
    $variables['list'] = $variables['elements']['list'];
  }
  if (isset($variables['elements']['file']) && !empty($variables['elements']['file'])) {
    $variables['file'] = $variables['elements']['file'];
  }
  if (isset($variables['elements']['minutes_of_discussion']) && !empty($variables['elements']['minutes_of_discussion'])) {
    $variables['minutes_of_discussion'] = $variables['elements']['minutes_of_discussion'];
  }
  if (isset($variables['elements']['decision_announcement']) && !empty($variables['elements']['decision_announcement'])) {
    $variables['decision_announcement'] = $variables['elements']['decision_announcement'];
  }
}

/**
 * Prepares variables for paatokset_ahjo templates.
 *
 * Default template: block--policymaker-members.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An array of elements to display in view mode.
 */
function template_preprocess_block__policymaker_members(array &$variables) {
  $variables['#attached']['library'][] = 'paatokset_policymakers/policymaker_members';
  $node = \Drupal::routeMatch()->getParameter('node');

  $variables['policymaker_name'] = $node->get('field_ahjo_title')->value;
  $variables['policymaker_id'] = $node->get('field_policymaker_id')->value;
  $variables['policymaker_type'] = $node->get('field_organization_type')->value;

  // Helpful $content variable for templates.
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
  if (isset($variables['elements']['#block__policymaker_members'])) {
    $variables['entity'] = $variables['elements']['#block__policymaker_members'];
  }
}

/**
 * Implements hook_pathauto_pattern_alter().
 *
 * Custom node path for Viranhaltija decisionmakers, add org name to URL.
 */
function paatokset_policymakers_pathauto_pattern_alter(&$pattern, array $context) {
  // Only act on node context.
  if (!isset($context['module'], $context['data']['node']) || $context['module'] !== 'node') {
    return;
  }
  /** @var \Drupal\node\NodeInterface $node */
  $node = $context['data']['node'];

  // Only act on policymaker nodes and make sure fields exist.
  if (!$node->bundle() === 'policymaker' || !$node->hasField('field_ahjo_title') || !$node->hasField('field_dm_org_name') || !$node->hasField('field_organization_type')) {
    return;
  }

  $allowed_types = [
    'Viranhaltija',
    'Luottamushenkilö',
  ];

  // Only act on Viranhaltija decisionmakers.
  if (!in_array($node->get('field_organization_type')->value, $allowed_types)) {
    return;
  }

  // Special case: Dont' add org name to Pormestari URL.
  if ($node->get('field_ahjo_title')->value === 'Pormestari') {
    return;
  }

  // If org name exists, add it to the path.
  if (!$node->get('field_dm_org_name')->isEmpty()) {
    $pattern->setPattern('paattajat/[node:field_ahjo_title]-[node:field_dm_org_name:value]');
    return;
  }
}

/**
 * Implements hook_preprocess_html().
 */
function paatokset_policymakers_preprocess_html(&$variables) {
  if(isset($variables['page']['sidebar_first']) && array_key_exists('policymakersidenavigation', $variables['page']['sidebar_first'])) {
    $variables['attributes']['class'][] = 'page-type--policymaker';
  }
}

/**
 * Implements hook_preprocess_page().
 */
function paatokset_policymakers_preprocess_page(&$variables) {
  if(isset($variables['page']['content']) && array_key_exists('paatoksetpolicymakersearch', $variables['page']['content'])) {
    $variables['move_before_content'] = TRUE;
  }
}
