_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
ignored_config_entities:
  - 'hdbt_admin_tools.site_settings:site_settings'
  - paatokset_ahjo_api.default_texts
  - 'system.site:page.front'
  - paatokset_ahjo_proxy.blacklist
  - 'paatokset_ahjo_api.disallowed_decisions.*'
  - paatokset_ahjo_openid.settings
  - paatokset_ahjo_proxy.settings
