_core:
  default_config_hash: NGxFi-xycxrzrGVZtCUl7MACi0jVRk130tNabvIN6ng
content_root: ''
assertiveness: smart
no_load: ''
embedded_content_warning: ''
download_links: ''
ignore_link_strings: ''
link_ignore_selector: 'svg.ext, svg.mailto, .link-purpose-text'
hidden_handlers: ''
ignore_containers: ''
allow_overflow: ''
