<?php


/**
 * Implements hook_theme().
 */
function paatokset_news_importer_theme($exitsting, $type, $theme, $path) {
  return [
    'node__imported_article' => [
      'base hook' => 'node'
    ],
    'node__imported_article__tiny_teaser' => [
      'base hook' => 'node'
    ],
    'views_view_unformatted__imported_articles' => [
      'base hook' => 'view'
    ]
  ];
}

/**
 * Implements hook_preprocess_page().
 */
function paatokset_news_importer_preprocess_page(array &$variables) {
  if(isset($variables['node']) && $variables['node']->getType() === 'imported_article') {
    $variables['page_has_sidebar'] = true;
    $variables['move_before_content'] = true;
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function paatokset_news_importer_preprocess_node__imported_article(&$variables) {
  $variables['content']['lead'] = $variables['node']->body->view('teaser');
  $variables['content']['lead_image'] = $variables['node']->field_image_url->uri;
  $variables['content']['published'] = $variables['node']->field_published->date->getTimeStamp();
}
