<?php


/**
 * Implements hook_theme().
 */
function paatokset_news_importer_theme($exitsting, $type, $theme, $path) {
  return [
    'node__imported_article' => [
      'base hook' => 'node'
    ],
    'page__imported_article' => [
      'base hook' => 'page'
    ],
    'views_view_unformatted__imported_articles' => [
      'base hook' => 'view'
    ]
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function helfi_paatokset_preprocess_node__imported_article(&$variables) {
  $variables['content']['lead'] = $variables['node']->body->view('teaser');
  $variables['content']['lead_image'] = $variables['node']->field_image_url->uri;
  $variables['content']['published'] = $variables['node']->field_published->date->getTimeStamp();
}
