# Cases

### Get cases with default values
GET {{ahjo_proxy}}/cases?
    api-key={{api_key}}

### Get cases with optional values
@handledsince=2025-01-01T00:00:00
@end=2025-05-01T00:00:00
@size=30

GET {{ahjo_proxy}}/cases?
    api-key={{api_key}}&
    handledsince={{handledsince}}&
    end={{end}}&
    size={{size}}

### Get a single case with case ID
@case_id=HEL-2022-005518

GET {{ahjo_proxy}}/cases/single/
    {{case_id}}?
    api-key={{api_key}}

