# Decision maker&#10&#10### Get a single decisionmaker with decisionmaker ID&#10@decision_maker_id=02900&#10&#10GET {{ahjo_proxy}}/decisionmaker/single/&#10    {{decision_maker_id}}?&#10    api-key={{api_key}}&#10&#10### Get a single trustee by ID&#10@trustee_id=change_me&#10&#10GET {{ahjo_proxy}}/trustees/single/{{trustee_id}}?&#10    api-key={{api_key}}&#10