# Decisions&#10&#10### Get decisions with default values&#10GET {{ahjo_proxy}}/decisions?&#10    api-key={{api_key}}&#10&#10### Get decisions with optional values&#10@handledsince=2025-01-01T00:00:00&#10@end=2025-05-01T00:00:00&#10@size=30&#10@decisionmaker_id=02900&#10@meeting_id=0290020254&#10&#10GET {{ahjo_proxy}}/decisions?&#10    api-key={{api_key}}&&#10    handledsince={{handledsince}}&&#10    end={{end}}&&#10    size={{size}}&&#10    decisionmaker_id={{decisionmaker_id}}&&#10    meeting_id={{meeting_id}}&#10&#10### Get a single decision with decision ID&#10@decision_id=0129BBEF-9DE9-4696-BB86-06299CF5AF41&#10&#10GET {{ahjo_proxy}}/decisions/single/&#10    {{decision_id}}?&#10    api-key={{api_key}}&#10