# Organization&#10&#10### Get a single organization by ID&#10@organization_id=00400&#10@steps=2&#10&#10GET {{ahjo_proxy}}/organization/single/{{organization_id}}?&#10    api-key={{api_key}}&#10&#10### Get an organization chart in Finnish by organization ID&#10GET {{ahjo_proxy}}/org-chart/{{organization_id}}/{{steps}}?&#10    api-key={{api_key}}&#10&#10### Get an organization chart in Swedish by organization ID&#10GET {{ahjo_proxy_sv}}/org-chart/{{organization_id}}/{{steps}}?&#10    api-key={{api_key}}&#10&#10# Ahjo API&#10### Get an organization composition by ID&#10&#10GET {{ahjo_api}}/org_composition/{{organization_id}}&#10