popup_agreed: {  }
popup_agree_button_message: Accepterar
popup_hide_button_message: Dölj
popup_info: {  }
popup_link: /cookie-installningar
disagree_button_label: 'Nej, tack'
withdraw_message: {  }
withdraw_action_button_label: 'Återkalla samtycke'
withdraw_tab_button_label: Sekretessinställningar
accept_all_categories_button_label: 'Acceptera alla cookies'
