<?php

/**
 * @file
 * Primary module hooks for Paatokset allu module.
 */

declare(strict_types=1);

/**
 * Implements hook_theme().
 */
function paatokset_allu_theme() : array {
  return [
    'allu_decisions_search_block' => [
      'variables' => [],
      'template' => 'allu-decisions-search-block',
    ],
  ];
}

/**
 * Implements hook_preprocess_paragraph__HOOK().
 */
function paatokset_allu_preprocess_paragraph__allu_decisions_search(array &$variables) {
  $variables['#attached']['drupalSettings']['helfi_react_search']['elastic_proxy_url'] = \Drupal::config('elastic_proxy.settings')->get('elastic_proxy_url');
}
