<?php

/**
 * @file
 * Primary module hooks for Paatokset allu module.
 */

declare(strict_types=1);

use Drupal\helfi_platform_config\DTO\ParagraphTypeCollection;
use Drupal\search_api\IndexInterface;

/**
 * Implements hook_preprocess_paragraph__HOOK().
 */
function paatokset_allu_preprocess_paragraph__allu_decisions_search(array &$variables) {
  $variables['#attached']['drupalSettings']['helfi_react_search']['elastic_proxy_url'] = \Drupal::config('elastic_proxy.settings')->get('elastic_proxy_url');
}

/**
 * Implements hook_helfi_paragraph_types().
 */
function paatokset_allu_helfi_paragraph_types() {
  return [
    new ParagraphTypeCollection('node', 'page', 'field_content', 'allu_decisions_search', 19),
  ];
}
